name: CDK Deploy

on:
  push:
    paths:
      - 'infra/**'

jobs:
  cdk_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.recluse_web_access_key }}
          aws-secret-access-key: ${{ secrets.recluse_web_secret_key }}
          aws-region: us-west-2

      - name: NPM install
        run: cd infra && npm install

      - name: CDK diff
        uses: youyo/aws-cdk-github-actions@master
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
          working_dir: 'infra'

      - name: CDK synth
        uses: youyo/aws-cdk-github-actions@master
        with:
          cdk_subcommand: 'synth'
          cdk_version: '1.36.1'
          working_dir: 'infra'

      - name: CDK deploy
        uses: youyo/aws-cdk-github-actions@master
        with:
          working_dir: 'infra'
          cdk_subcommand: 'deploy'
          cdk_stack: 'RecluseWebInfraStack'
          actions_comment: false
          args: '--require-approval never'
