name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
          token: ${{ secrets.RECLUSE_CI_ROBOT_TOKEN }}
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.RECLUSE_CI_ROBOT_TOKEN }}
          cname: www.recluse-games.com
          branch: gh-pages
          repo: recluse-games/www.recluse-games.com
        env:
          - GITHUB_ACTOR: "recluse-ci-robot"